### ISSUE TITLE
Mage can't mage bedrock blocks

### ISSUE THREAD

**Issue by stompman** [bluefireoly/hglabor-kits#13]
Probably an artifact of a time where you could replace bedrock with endstone to create a voidtrap. Now, its a pretty much useless feature that doesn't fix any bugs. Also, as someone who likes to trap on bedrock level, its a bit frustrating because im not able to mage down a teammate properly.

**Comment by ghost** [comment]
Mage gibt es nichtmal in dieser API???

**Comment by stompman** [comment]
Ja sorry wusste nicht wo ich den bug reporten sollte

**Comment by ghost** [comment]
Die Kits werden ja in die neue API übernommen und dabei alle Bugs ausgebügelt, kannst das issue dann schließen (oder im anderen Repo Reporten).

**Comment by stompman** [comment]
Wo genau? Sorry hab 0 Plan von GitHub lmao

**Comment by ghost** [comment]
https://github.com/HGLabor/HGLaborKitAPI2.0
